services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    hostname: mosquitto
    ports:
      - "18883:1883"
    restart: unless-stopped
    volumes:
      - ./simple-mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  tc31-xar-um:
    image: ghcr.io/ietv/tc3_xar_um_ietv:latest
    hostname: tc31-xar-um
    restart: unless-stopped
    depends_on:
      - mosquitto
    privileged: true
    volumes:
      - /dev/hugepages:/dev/hugepages:rw
    environment:
      AMS_NETID: 15.15.15.15.1.1
